# Generated by Django 4.2.4 on 2023-08-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0002_imageasset_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageasset',
            name='uploadDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
