# Generated by Django 4.2.4 on 2023-09-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0005_aboutdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftCardHeading', models.TextField()),
                ('leftCardText', models.TextField()),
                ('leftCardImageUrl', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
