# Generated by Django 4.2.4 on 2023-09-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0006_leftcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rightCardHeading', models.TextField()),
                ('rightCardText', models.TextField()),
                ('rightCardImageUrl', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
