# Generated by Django 4.2.4 on 2023-09-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0008_offeredservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiddleGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gridTitle', models.TextField()),
                ('gridMessage', models.TextField()),
                ('gridRedirectionUrl', models.TextField()),
            ],
        ),
    ]
