# Generated by Django 4.2.4 on 2023-09-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0009_middlegrid'),
    ]

    operations = [
        migrations.AddField(
            model_name='middlegrid',
            name='gridButtonText',
            field=models.TextField(blank=True),
        ),
    ]
