# Generated by Django 4.2.4 on 2023-09-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0010_middlegrid_gridbuttontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venueName', models.TextField()),
                ('venueDescription', models.TextField()),
                ('venueImageUrl', models.TextField()),
                ('isFeatured', models.BooleanField()),
            ],
        ),
    ]
