# Generated by Django 4.2.4 on 2023-09-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0011_venueitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestName', models.TextField()),
                ('guestPosition', models.TextField()),
                ('guestComment', models.TextField()),
                ('guestImageUrl', models.TextField()),
            ],
        ),
    ]
