# Generated by Django 4.2.4 on 2023-09-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0012_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happyGuests', models.IntegerField()),
                ('hostedEvents', models.IntegerField()),
                ('staffCount', models.IntegerField()),
                ('venueCount', models.IntegerField()),
            ],
        ),
    ]
