# Generated by Django 4.2.4 on 2023-09-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0019_alter_messageentrynames_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleContactMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.TextField()),
                ('UserEmail', models.TextField()),
                ('UserSubject', models.TextField()),
                ('UserMessage', models.TextField()),
                ('dateSent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
