# Generated by Django 4.2.4 on 2023-09-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0020_simplecontactmessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHolders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.TextField()),
            ],
        ),
    ]
