# Generated by Django 4.2.4 on 2023-09-05 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0021_emailholders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simplecontactmessages',
            options={'ordering': ('dateSent',)},
        ),
        migrations.CreateModel(
            name='EmailReplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replyMessage', models.TextField()),
                ('associatedHolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_replies', to='mariadmin.emailholders')),
            ],
        ),
    ]
