# Generated by Django 4.2.4 on 2023-09-06 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0022_alter_simplecontactmessages_options_emailreplies'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailreplies',
            name='dateCreated',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 9, 6, 6, 55, 24, 218646)),
        ),
    ]
