# Generated by Django 4.2.4 on 2023-09-06 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0023_emailreplies_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailreplies',
            name='dateCreated',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
