# Generated by Django 4.2.4 on 2023-09-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0024_alter_emailreplies_datecreated'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='emailreplies',
            options={'ordering': ('-dateCreated',)},
        ),
    ]
