# Generated by Django 4.2.4 on 2023-09-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0025_postcategory_alter_emailreplies_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postHeading', models.TextField()),
                ('postHeadingImage', models.TextField()),
                ('postTopBody', models.TextField()),
                ('postMainImage', models.TextField()),
                ('postLeftSubImage', models.TextField(blank=True, null=True)),
                ('postRightSubImage', models.TextField(blank=True, null=True)),
                ('postPossibleCategories', models.TextField(default='general')),
                ('postDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
