# Generated by Django 4.2.4 on 2023-09-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0026_postitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='postLowerBody',
            field=models.TextField(default=''),
        ),
    ]
