# Generated by Django 4.2.4 on 2023-09-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0028_alter_postitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='postFeatured',
            field=models.BooleanField(default=False),
        ),
    ]
