# Generated by Django 4.2.4 on 2023-09-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0029_postitem_postfeatured'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posterName', models.TextField()),
                ('commentDate', models.DateTimeField(auto_now_add=True)),
                ('postComment', models.TextField()),
            ],
        ),
    ]
