# Generated by Django 4.2.4 on 2023-09-09 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0030_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='attachedPost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_comments', to='mariadmin.postitem'),
        ),
    ]
