# Generated by Django 4.2.4 on 2023-09-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0031_postcomment_attachedpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ('-commentDate',)},
        ),
    ]
