# Generated by Django 4.2.4 on 2023-09-14 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0035_vendorpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpage',
            name='vendorDistrict',
            field=models.TextField(default='Kampala'),
        ),
        migrations.CreateModel(
            name='VendorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.TextField()),
                ('serviceBriefDescription', models.TextField(max_length=180)),
                ('serviceDetailedDescription', models.TextField()),
                ('servicePreviewImage', models.TextField()),
                ('associatedVendorPage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_services', to='mariadmin.vendorpage')),
            ],
        ),
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageHeaderText', models.TextField()),
                ('vendorSlogan', models.TextField()),
                ('vendorContact', models.TextField()),
                ('vendorEmail', models.TextField()),
                ('businessLocation', models.TextField()),
                ('associatedVendorPage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_detail', to='mariadmin.vendorpage')),
            ],
        ),
    ]
