# Generated by Django 4.2.4 on 2023-09-14 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0038_vendorservice_dateadded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorservice',
            options={'ordering': ('-dateAdded',)},
        ),
    ]
