# Generated by Django 4.2.4 on 2023-09-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0040_imageasset_isgalleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachedEmail', models.TextField()),
                ('generatedCode', models.TextField()),
                ('expiryTime', models.DateTimeField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
