# Generated by Django 4.2.4 on 2023-09-18 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mariadmin', '0042_adminpermissions_adminnextofkins'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextOfKinItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associatedPermissions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='their_user_profile', to='mariadmin.adminpermissions')),
                ('associatedUserObject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='their_access_tag', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
