# Generated by Django 4.2.4 on 2023-09-18 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0043_nextofkinitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminnextofkins',
            name='associatedPermissions',
        ),
        migrations.AddField(
            model_name='adminpermissions',
            name='associatedAdmin',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_permissions', to='mariadmin.adminnextofkins'),
        ),
    ]
