# Generated by Django 4.2.4 on 2023-09-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0044_remove_adminnextofkins_associatedpermissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnextofkins',
            name='adminHasPermissions',
            field=models.BooleanField(default=False),
        ),
    ]
