# Generated by Django 4.2.4 on 2023-09-18 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0045_adminnextofkins_adminhaspermissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminnextofkins',
            name='adminHasPermissions',
        ),
    ]
