# Generated by Django 4.2.4 on 2023-09-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0046_remove_adminnextofkins_adminhaspermissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotAccessibleYet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminEmailAddress', models.TextField()),
            ],
        ),
    ]
