# Generated by Django 4.2.4 on 2023-09-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0047_notaccessibleyet'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteHeadingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.TextField()),
            ],
        ),
    ]
