# Generated by Django 4.2.4 on 2023-09-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0048_websiteheadingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpage',
            name='pageImageLogo',
            field=models.TextField(default=''),
        ),
    ]
