# Generated by Django 4.2.4 on 2023-09-19 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0051_remove_venueitem_venueimageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueImageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.TextField()),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('associatedVenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_venue_images', to='mariadmin.venueitem')),
            ],
        ),
    ]
