# Generated by Django 4.2.4 on 2023-09-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0052_venueimageitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venueimageitem',
            options={'ordering': ('-dateAdded',)},
        ),
    ]
