# Generated by Django 4.2.4 on 2023-09-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0053_alter_venueimageitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='forMariaHillGardens',
            field=models.BooleanField(default=False),
        ),
    ]
