# Generated by Django 4.2.4 on 2023-09-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0056_eventsservicescontacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromToMeta', models.TextField()),
                ('emailContact', models.TextField()),
                ('phoneContact', models.TextField(default='')),
                ('eventCategory', models.TextField()),
                ('guestNumber', models.IntegerField()),
                ('bookingDetails', models.TextField()),
                ('dateSent', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-dateSent',),
            },
        ),
    ]
