# Generated by Django 4.2.4 on 2023-09-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0057_bookingmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingMessage',
        ),
    ]
