# Generated by Django 4.2.4 on 2023-09-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0058_delete_bookingmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingFormDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formText', models.TextField()),
                ('imageUrl', models.TextField()),
            ],
        ),
    ]
