# Generated by Django 4.2.4 on 2023-09-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0059_bookingformdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutImageUrl', models.TextField()),
            ],
        ),
    ]
