# Generated by Django 4.2.4 on 2023-09-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0060_aboutimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueitem',
            name='venueContact',
            field=models.TextField(default='Missing'),
        ),
    ]
