# Generated by Django 4.2.4 on 2023-12-14 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0061_venueitem_venuecontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.TextField()),
                ('clientEmailAddress', models.TextField()),
                ('dateOfRequest', models.DateTimeField(auto_now_add=True, null=True)),
                ('requestParticulars', models.TextField(default='')),
                ('venueUsageDate', models.DateTimeField()),
                ('numberOfGuests', models.IntegerField()),
            ],
            options={
                'ordering': ('-dateOfRequest',),
            },
        ),
        migrations.CreateModel(
            name='BookingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isIssued', models.BooleanField(default=False)),
                ('isSatisfied', models.BooleanField(default=False)),
                ('transactionBill', models.IntegerField()),
                ('satisfiedDate', models.DateTimeField()),
                ('issuedDate', models.DateTimeField()),
                ('whoIssuedTransaction', models.TextField()),
                ('detailsOfTransaction', models.TextField()),
                ('clientDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_transaction', to='mariadmin.bookingrequest')),
            ],
            options={
                'ordering': ('-issuedDate',),
            },
        ),
    ]
