# Generated by Django 4.2.4 on 2023-12-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0062_bookingrequest_bookingtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='venueUsageDate',
            field=models.DateField(),
        ),
    ]
