# Generated by Django 4.2.4 on 2023-12-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0064_bookingrequest_eventcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
    ]
