# Generated by Django 4.2.4 on 2023-12-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0065_bookingrequest_iscomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='numberOfDays',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='timeStamps',
            field=models.TextField(default=''),
        ),
    ]
