# Generated by Django 4.2.4 on 2023-12-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0066_bookingrequest_numberofdays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='venueEndDate',
            field=models.DateField(null=True),
        ),
    ]
