# Generated by Django 4.2.4 on 2023-12-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0067_bookingrequest_venueenddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingtransaction',
            old_name='isIssued',
            new_name='isVisible',
        ),
    ]
