# Generated by Django 4.2.4 on 2023-12-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0068_rename_isissued_bookingtransaction_isvisible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtransaction',
            name='detailsOfTransaction',
            field=models.TextField(default=''),
        ),
    ]
