# Generated by Django 4.2.4 on 2023-12-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0070_alter_bookingtransaction_issueddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtransaction',
            name='satisfiedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
