# Generated by Django 4.2.4 on 2023-12-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mariadmin', '0072_bookingrequest_haslinkissued'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtransaction',
            name='clientEmailAddress',
            field=models.TextField(default=''),
        ),
    ]
