# Generated by Django 4.2.4 on 2023-09-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_alter_userprofileimage_userimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileimage',
            name='userImage',
        ),
        migrations.AddField(
            model_name='userprofileimage',
            name='userProfileImage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
